// BASE LIBS
var _CONFIG={LOGGING:!0};var Language=new function(){this.en={Validation:{urlshort:"Please enter a valid url: Eg: mysite.com",alphanumeric:"Letters, numbers, and dashes only please",lettersonly:"Letters only please",letterswithbasicpunc:"Letters or punctuation only please",letterswithwhitespace:"Letters with white spaces only please",alphanumericnodash:"Letters and numbers only please",alphanumericwhitespace:"Letters and numbers only please",nowhitespace:"No white space please",ziprange:"Your ZIP-code must be in the range 902xx-xxxx to 905-xx-xxxx",
integer:"A positive or negative non-decimal number please",vinUS:"The specified vehicle identification number (VIN) is invalid",dateITA:"Please enter a correct date","user-password-retype":"Please type in the same password",maxWords:"Please enter {0} words or less",minWords:"Please enter at least {0} words",rangeWords:"Please enter between {0} and {1} words",valueNotEquals:"Value must not equal arg",required:"This field is required",remote:"Please fix this field",email:"Valid email address required",
url:"Please enter a valid URL",date:"Please enter a valid date",dateISO:"Please enter a valid date (ISO)",number:"Please enter a valid number",digits:"Please enter only digits",creditcard:"Please enter a valid credit card number",equalTo:"Please enter the same value again",accept:"Please enter a value with a valid extension",maxlength:"Please enter no more than {0} characters",minlength:"Please enter at least {0} characters",rangelength:"Please enter a value between {0} and {1} characters long",range:"Please enter a value between {0} and {1}",
max:"Please enter a value less than or equal to {0}",min:"Please enter a value greater than or equal to {0}"}};this.zh={}},Localization=Language.en;(function(b){b.extend(b.fn,{validate:function(a){if(this.length){var c=b.data(this[0],"validator");if(c)return c;this.attr("novalidate","novalidate");c=new b.validator(a,this[0]);b.data(this[0],"validator",c);c.settings.onsubmit&&(a=this.find("input, button"),a.filter(".cancel").click(function(){c.cancelSubmit=!0}),c.settings.submitHandler&&a.filter(":submit").click(function(){c.submitButton=this}),this.submit(function(a){function f(){if(c.settings.submitHandler){if(c.submitButton)var a=b("<input type='hidden'/>").attr("name",
c.submitButton.name).val(c.submitButton.value).appendTo(c.currentForm);c.settings.submitHandler.call(c,c.currentForm);c.submitButton&&a.remove();return!1}return!0}c.settings.debug&&a.preventDefault();if(c.cancelSubmit)return c.cancelSubmit=!1,f();if(c.form())return c.pendingRequest?(c.formSubmitted=!0,!1):f();c.focusInvalid();return!1}));return c}a&&a.debug&&window.console&&console.warn("nothing selected, can't validate, returning nothing")},valid:function(){if(b(this[0]).is("form"))return this.validate().form();
var a=!0,c=b(this[0].form).validate();this.each(function(){a&=c.element(this)});return a},removeAttrs:function(a){var c={},d=this;b.each(a.split(/\s/),function(a,b){c[b]=d.attr(b);d.removeAttr(b)});return c},rules:function(a,c){var d=this[0];if(a){var f=b.data(d.form,"validator").settings,g=f.rules,r=b.validator.staticRules(d);switch(a){case "add":b.extend(r,b.validator.normalizeRule(c));g[d.name]=r;c.messages&&(f.messages[d.name]=b.extend(f.messages[d.name],c.messages));break;case "remove":if(!c)return delete g[d.name],
r;var u={};b.each(c.split(/\s/),function(a,b){u[b]=r[b];delete r[b]});return u}}d=b.validator.normalizeRules(b.extend({},b.validator.metadataRules(d),b.validator.classRules(d),b.validator.attributeRules(d),b.validator.staticRules(d)),d);d.required&&(f=d.required,delete d.required,d=b.extend({required:f},d));return d}});b.extend(b.expr[":"],{blank:function(a){return!b.trim(""+a.value)},filled:function(a){return!!b.trim(""+a.value)},unchecked:function(a){return!a.checked}});b.validator=function(a,c){this.settings=
b.extend(!0,{},b.validator.defaults,a);this.currentForm=c;this.init()};b.validator.format=function(a,c){if(1==arguments.length)return function(){var c=b.makeArray(arguments);c.unshift(a);return b.validator.format.apply(this,c)};2<arguments.length&&c.constructor!=Array&&(c=b.makeArray(arguments).slice(1));c.constructor!=Array&&(c=[c]);b.each(c,function(b,c){a=a.replace(RegExp("\\{"+b+"\\}","g"),c)});return a};b.extend(b.validator,{defaults:{messages:{},groups:{},rules:{},errorClass:"error",validClass:"valid",
errorElement:"label",focusInvalid:!0,errorContainer:b([]),errorLabelContainer:b([]),onsubmit:!0,ignore:":hidden",ignoreTitle:!1,onfocusin:function(a){this.lastActive=a;this.settings.focusCleanup&&!this.blockFocusCleanup&&(this.settings.unhighlight&&this.settings.unhighlight.call(this,a,this.settings.errorClass,this.settings.validClass),this.addWrapper(this.errorsFor(a)).hide())},onfocusout:function(a){!this.checkable(a)&&(a.name in this.submitted||!this.optional(a))&&this.element(a)},onkeyup:function(a){(a.name in
this.submitted||a==this.lastElement)&&this.element(a)},onclick:function(a){a.name in this.submitted?this.element(a):a.parentNode.name in this.submitted&&this.element(a.parentNode)},highlight:function(a,c,d){"radio"===a.type?this.findByName(a.name).addClass(c).removeClass(d):b(a).addClass(c).removeClass(d)},unhighlight:function(a,c,d){"radio"===a.type?this.findByName(a.name).removeClass(c).addClass(d):b(a).removeClass(c).addClass(d)}},setDefaults:function(a){b.extend(b.validator.defaults,a)},messages:{required:Localization.Validation.required,
remote:Localization.Validation.remote,email:Localization.Validation.email,url:Localization.Validation.url,date:Localization.Validation.date,dateISO:Localization.Validation.dateISO,number:Localization.Validation.number,digits:Localization.Validation.digits,creditcard:Localization.Validation.creditcard,equalTo:Localization.Validation.equalTo,accept:Localization.Validation.accept,maxlength:b.validator.format(Localization.Validation.maxlength),minlength:b.validator.format(Localization.Validation.minlength),
rangelength:b.validator.format(Localization.Validation.rangelength),range:b.validator.format(Localization.Validation.range),max:b.validator.format(Localization.Validation.max),min:b.validator.format(Localization.Validation.min)},autoCreateRanges:!1,prototype:{init:function(){function a(a){var c=b.data(this[0].form,"validator"),d="on"+a.type.replace(/^validate/,"");c.settings[d]&&c.settings[d].call(c,this[0],a)}this.labelContainer=b(this.settings.errorLabelContainer);this.errorContext=this.labelContainer.length&&
this.labelContainer||b(this.currentForm);this.containers=b(this.settings.errorContainer).add(this.settings.errorLabelContainer);this.submitted={};this.valueCache={};this.pendingRequest=0;this.pending={};this.invalid={};this.reset();var c=this.groups={};b.each(this.settings.groups,function(a,d){b.each(d.split(/\s/),function(b,d){c[d]=a})});var d=this.settings.rules;b.each(d,function(a,c){d[a]=b.validator.normalizeRule(c)});b(this.currentForm).validateDelegate("[type='text'], [type='password'], [type='file'], select, textarea, [type='number'], [type='search'] ,[type='tel'], [type='url'], [type='email'], [type='datetime'], [type='date'], [type='month'], [type='week'], [type='time'], [type='datetime-local'], [type='range'], [type='color'] ",
"focusin focusout keyup",a).validateDelegate("[type='radio'], [type='checkbox'], select, option","click",a);this.settings.invalidHandler&&b(this.currentForm).bind("invalid-form.validate",this.settings.invalidHandler)},form:function(){this.checkForm();b.extend(this.submitted,this.errorMap);this.invalid=b.extend({},this.errorMap);this.valid()||b(this.currentForm).triggerHandler("invalid-form",[this]);this.showErrors();return this.valid()},checkForm:function(){this.prepareForm();for(var a=0,b=this.currentElements=
this.elements();b[a];a++)this.check(b[a]);return this.valid()},element:function(a){this.lastElement=a=this.validationTargetFor(this.clean(a));this.prepareElement(a);this.currentElements=b(a);var c=this.check(a);c?delete this.invalid[a.name]:this.invalid[a.name]=!0;this.numberOfInvalids()||(this.toHide=this.toHide.add(this.containers));this.showErrors();return c},showErrors:function(a){if(a){b.extend(this.errorMap,a);this.errorList=[];for(var c in a)this.errorList.push({message:a[c],element:this.findByName(c)[0]});
this.successList=b.grep(this.successList,function(b){return!(b.name in a)})}this.settings.showErrors?this.settings.showErrors.call(this,this.errorMap,this.errorList):this.defaultShowErrors()},resetForm:function(){b.fn.resetForm&&b(this.currentForm).resetForm();this.submitted={};this.lastElement=null;this.prepareForm();this.hideErrors();this.elements().removeClass(this.settings.errorClass)},numberOfInvalids:function(){return this.objectLength(this.invalid)},objectLength:function(a){var b=0,d;for(d in a)b++;
return b},hideErrors:function(){this.addWrapper(this.toHide).hide()},valid:function(){return 0==this.size()},size:function(){return this.errorList.length},focusInvalid:function(){if(this.settings.focusInvalid)try{b(this.findLastActive()||this.errorList.length&&this.errorList[0].element||[]).filter(":visible").focus().trigger("focusin")}catch(a){}},findLastActive:function(){var a=this.lastActive;return a&&1==b.grep(this.errorList,function(b){return b.element.name==a.name}).length&&a},elements:function(){var a=
this,c={};return b(this.currentForm).find("input, select, textarea").not(":submit, :reset, :image, [disabled]").not(this.settings.ignore).filter(function(){!this.name&&a.settings.debug&&window.console&&console.error("%o has no name assigned",this);return this.name in c||!a.objectLength(b(this).rules())?!1:c[this.name]=!0})},clean:function(a){return b(a)[0]},errors:function(){return b(this.settings.errorElement+"."+this.settings.errorClass,this.errorContext)},reset:function(){this.successList=[];this.errorList=
[];this.errorMap={};this.toShow=b([]);this.toHide=b([]);this.currentElements=b([])},prepareForm:function(){this.reset();this.toHide=this.errors().add(this.containers)},prepareElement:function(a){this.reset();this.toHide=this.errorsFor(a)},check:function(a){a=this.validationTargetFor(this.clean(a));var c=b(a).rules(),d=!1,f;for(f in c){var g={method:f,parameters:c[f]};try{var r=b.validator.methods[f].call(this,a.value.replace(/\r/g,""),a,g.parameters);if("dependency-mismatch"==r)d=!0;else{d=!1;if("pending"==
r){this.toHide=this.toHide.not(this.errorsFor(a));return}if(!r)return this.formatAndAdd(a,g),!1}}catch(u){throw this.settings.debug&&window.console&&console.log("exception occured when checking element "+a.id+", check the '"+g.method+"' method",u),u;}}if(!d)return this.objectLength(c)&&this.successList.push(a),!0},customMetaMessage:function(a,c){if(b.metadata){var d=this.settings.meta?b(a).metadata()[this.settings.meta]:b(a).metadata();return d&&d.messages&&d.messages[c]}},customMessage:function(a,
b){var d=this.settings.messages[a];return d&&(d.constructor==String?d:d[b])},findDefined:function(){for(var a=0;a<arguments.length;a++)if(void 0!==arguments[a])return arguments[a]},defaultMessage:function(a,c){return this.findDefined(this.customMessage(a.name,c),this.customMetaMessage(a,c),!this.settings.ignoreTitle&&a.title||void 0,b.validator.messages[c],"<strong>Warning: No message defined for "+a.name+"</strong>")},formatAndAdd:function(a,b){var d=this.defaultMessage(a,b.method),f=/\$?\{(\d+)\}/g;
"function"==typeof d?d=d.call(this,b.parameters,a):f.test(d)&&(d=jQuery.format(d.replace(f,"{$1}"),b.parameters));this.errorList.push({message:d,element:a});this.errorMap[a.name]=d;this.submitted[a.name]=d},addWrapper:function(a){this.settings.wrapper&&(a=a.add(a.parent(this.settings.wrapper)));return a},defaultShowErrors:function(){for(var a=0;this.errorList[a];a++){var b=this.errorList[a];this.settings.highlight&&this.settings.highlight.call(this,b.element,this.settings.errorClass,this.settings.validClass);
this.showLabel(b.element,b.message)}this.errorList.length&&(this.toShow=this.toShow.add(this.containers));if(this.settings.success)for(a=0;this.successList[a];a++)this.showLabel(this.successList[a]);if(this.settings.unhighlight){a=0;for(b=this.validElements();b[a];a++)this.settings.unhighlight.call(this,b[a],this.settings.errorClass,this.settings.validClass)}this.toHide=this.toHide.not(this.toShow);this.hideErrors();this.addWrapper(this.toShow).show()},validElements:function(){return this.currentElements.not(this.invalidElements())},
invalidElements:function(){return b(this.errorList).map(function(){return this.element})},showLabel:function(a,c){var d=this.errorsFor(a);d.length?(d.removeClass(this.settings.validClass).addClass(this.settings.errorClass),d.attr("generated")&&d.html(c)):(d=b("<"+this.settings.errorElement+"/>").attr({"for":this.idOrName(a),generated:!0}).addClass(this.settings.errorClass).html(c||""),this.settings.wrapper&&(d=d.hide().show().wrap("<"+this.settings.wrapper+"/>").parent()),this.labelContainer.append(d).length||
(this.settings.errorPlacement?this.settings.errorPlacement(d,b(a)):d.insertAfter(a)));!c&&this.settings.success&&(d.text(""),"string"==typeof this.settings.success?d.addClass(this.settings.success):this.settings.success(d));this.toShow=this.toShow.add(d)},errorsFor:function(a){var c=this.idOrName(a);return this.errors().filter(function(){return b(this).attr("for")==c})},idOrName:function(a){return this.groups[a.name]||(this.checkable(a)?a.name:a.id||a.name)},validationTargetFor:function(a){this.checkable(a)&&
(a=this.findByName(a.name).not(this.settings.ignore)[0]);return a},checkable:function(a){return/radio|checkbox/i.test(a.type)},findByName:function(a){var c=this.currentForm;return b(document.getElementsByName(a)).map(function(b,f){return f.form==c&&f.name==a&&f||null})},getLength:function(a,c){switch(c.nodeName.toLowerCase()){case "select":return b("option:selected",c).length;case "input":if(this.checkable(c))return this.findByName(c.name).filter(":checked").length}return a.length},depend:function(a,
b){return this.dependTypes[typeof a]?this.dependTypes[typeof a](a,b):!0},dependTypes:{"boolean":function(a){return a},string:function(a,c){return!!b(a,c.form).length},"function":function(a,b){return a(b)}},optional:function(a){return!b.validator.methods.required.call(this,b.trim(a.value),a)&&"dependency-mismatch"},startRequest:function(a){this.pending[a.name]||(this.pendingRequest++,this.pending[a.name]=!0)},stopRequest:function(a,c){this.pendingRequest--;0>this.pendingRequest&&(this.pendingRequest=
0);delete this.pending[a.name];c&&0==this.pendingRequest&&this.formSubmitted&&this.form()?(b(this.currentForm).submit(),this.formSubmitted=!1):!c&&(0==this.pendingRequest&&this.formSubmitted)&&(b(this.currentForm).triggerHandler("invalid-form",[this]),this.formSubmitted=!1)},previousValue:function(a){return b.data(a,"previousValue")||b.data(a,"previousValue",{old:null,valid:!0,message:this.defaultMessage(a,"remote")})}},classRuleSettings:{required:{required:!0},email:{email:!0},url:{url:!0},date:{date:!0},
dateISO:{dateISO:!0},dateDE:{dateDE:!0},number:{number:!0},numberDE:{numberDE:!0},digits:{digits:!0},creditcard:{creditcard:!0}},addClassRules:function(a,c){a.constructor==String?this.classRuleSettings[a]=c:b.extend(this.classRuleSettings,a)},classRules:function(a){var c={};(a=b(a).attr("class"))&&b.each(a.split(" "),function(){this in b.validator.classRuleSettings&&b.extend(c,b.validator.classRuleSettings[this])});return c},attributeRules:function(a){var c={};a=b(a);for(var d in b.validator.methods){var f;
(f="required"===d&&"function"===typeof b.fn.prop?a.prop(d):a.attr(d))?c[d]=f:a[0].getAttribute("type")===d&&(c[d]=!0)}c.maxlength&&/-1|2147483647|524288/.test(c.maxlength)&&delete c.maxlength;return c},metadataRules:function(a){if(!b.metadata)return{};var c=b.data(a.form,"validator").settings.meta;return c?b(a).metadata()[c]:b(a).metadata()},staticRules:function(a){var c={},d=b.data(a.form,"validator");d.settings.rules&&(c=b.validator.normalizeRule(d.settings.rules[a.name])||{});return c},normalizeRules:function(a,
c){b.each(a,function(d,f){if(!1===f)delete a[d];else if(f.param||f.depends){var g=!0;switch(typeof f.depends){case "string":g=!!b(f.depends,c.form).length;break;case "function":g=f.depends.call(c,c)}g?a[d]=void 0!==f.param?f.param:!0:delete a[d]}});b.each(a,function(d,f){a[d]=b.isFunction(f)?f(c):f});b.each(["minlength","maxlength","min","max"],function(){a[this]&&(a[this]=Number(a[this]))});b.each(["rangelength","range"],function(){a[this]&&(a[this]=[Number(a[this][0]),Number(a[this][1])])});b.validator.autoCreateRanges&&
(a.min&&a.max&&(a.range=[a.min,a.max],delete a.min,delete a.max),a.minlength&&a.maxlength&&(a.rangelength=[a.minlength,a.maxlength],delete a.minlength,delete a.maxlength));a.messages&&delete a.messages;return a},normalizeRule:function(a){if("string"==typeof a){var c={};b.each(a.split(/\s/),function(){c[this]=!0});a=c}return a},addMethod:function(a,c,d){b.validator.methods[a]=c;b.validator.messages[a]=void 0!=d?d:b.validator.messages[a];3>c.length&&b.validator.addClassRules(a,b.validator.normalizeRule(a))},
methods:{required:function(a,c,d){if(!this.depend(d,c))return"dependency-mismatch";switch(c.nodeName.toLowerCase()){case "select":return(a=b(c).val())&&0<a.length;case "input":if(this.checkable(c))return 0<this.getLength(a,c);default:return 0<b.trim(a).length}},remote:function(a,c,d){if(this.optional(c))return"dependency-mismatch";var f=this.previousValue(c);this.settings.messages[c.name]||(this.settings.messages[c.name]={});f.originalMessage=this.settings.messages[c.name].remote;this.settings.messages[c.name].remote=
f.message;d="string"==typeof d&&{url:d}||d;if(this.pending[c.name])return"pending";if(f.old===a)return f.valid;f.old=a;var g=this;this.startRequest(c);var r={};r[c.name]=a;b.ajax(b.extend(!0,{url:d,mode:"abort",port:"validate"+c.name,dataType:"json",data:r,success:function(d){g.settings.messages[c.name].remote=f.originalMessage;var n=!0===d;if(n){var s=g.formSubmitted;g.prepareElement(c);g.formSubmitted=s;g.successList.push(c);g.showErrors()}else s={},d=d||g.defaultMessage(c,"remote"),s[c.name]=f.message=
b.isFunction(d)?d(a):d,g.showErrors(s);f.valid=n;g.stopRequest(c,n)}},d));return"pending"},minlength:function(a,c,d){return this.optional(c)||this.getLength(b.trim(a),c)>=d},maxlength:function(a,c,d){return this.optional(c)||this.getLength(b.trim(a),c)<=d},rangelength:function(a,c,d){a=this.getLength(b.trim(a),c);return this.optional(c)||a>=d[0]&&a<=d[1]},min:function(a,b,d){return this.optional(b)||a>=d},max:function(a,b,d){return this.optional(b)||a<=d},range:function(a,b,d){return this.optional(b)||
a>=d[0]&&a<=d[1]},email:function(a,b){return this.optional(b)||/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i.test(a)},
url:function(a,b){return this.optional(b)||/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i.test(a)},
date:function(a,b){return this.optional(b)||!/Invalid|NaN/.test(new Date(a))},dateISO:function(a,b){return this.optional(b)||/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(a)},number:function(a,b){return this.optional(b)||/^-?(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d+)?$/.test(a)},digits:function(a,b){return this.optional(b)||/^\d+$/.test(a)},creditcard:function(a,b){if(this.optional(b))return"dependency-mismatch";if(/[^0-9 -]+/.test(a))return!1;var d=0,f=0,g=!1;a=a.replace(/\D/g,"");for(var r=a.length-1;0<=r;r--){f=
a.charAt(r);f=parseInt(f,10);if(g&&9<(f*=2))f-=9;d+=f;g=!g}return 0==d%10},accept:function(a,b,d){d="string"==typeof d?d.replace(/,/g,"|"):"png|jpe?g|gif";return this.optional(b)||a.match(RegExp(".("+d+")$","i"))},equalTo:function(a,c,d){d=b(d).unbind(".validate-equalTo").bind("blur.validate-equalTo",function(){b(c).valid()});return a==d.val()}}});b.format=b.validator.format})(jQuery);
(function(b){var a={};if(b.ajaxPrefilter)b.ajaxPrefilter(function(b,c,g){c=b.port;"abort"==b.mode&&(a[c]&&a[c].abort(),a[c]=g)});else{var c=b.ajax;b.ajax=function(d){var f=("port"in d?d:b.ajaxSettings).port;return"abort"==("mode"in d?d:b.ajaxSettings).mode?(a[f]&&a[f].abort(),a[f]=c.apply(this,arguments)):c.apply(this,arguments)}}})(jQuery);
(function(b){!jQuery.event.special.focusin&&!jQuery.event.special.focusout&&document.addEventListener&&b.each({focus:"focusin",blur:"focusout"},function(a,c){function d(a){a=b.event.fix(a);a.type=c;return b.event.handle.call(this,a)}b.event.special[c]={setup:function(){this.addEventListener(a,d,!0)},teardown:function(){this.removeEventListener(a,d,!0)},handler:function(a){arguments[0]=b.event.fix(a);arguments[0].type=c;return b.event.handle.apply(this,arguments)}}});b.extend(b.fn,{validateDelegate:function(a,
c,d){return this.bind(c,function(c){var g=b(c.target);if(g.is(a))return d.apply(g,arguments)})}})})(jQuery);(function(){function b(a){return a.replace(/<.[^<>]*?>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/[0-9.(),;:!?%#$'"_+=\/-]*/g,"")}jQuery.validator.addMethod("maxWords",function(a,c,d){return this.optional(c)||b(a).match(/\b\w+\b/g).length<d},jQuery.validator.format(Localization.Validation.maxWords));jQuery.validator.addMethod("minWords",function(a,c,d){return this.optional(c)||b(a).match(/\b\w+\b/g).length>=d},jQuery.validator.format(Localization.Validation.minWords));jQuery.validator.addMethod("rangeWords",
function(a,c,d){return this.optional(c)||b(a).match(/\b\w+\b/g).length>=d[0]&&a.match(/bw+b/g).length<d[1]},jQuery.validator.format(Localization.Validation.rangeWords))})();jQuery.validator.addMethod("valueNotEquals",function(b,a,c){return c!=b},Localization.Validation.valueNotEquals);jQuery.validator.addMethod("filesize",function(b,a,c){return this.optional(a)||a.files[0].size<=c});
jQuery.validator.addMethod("urlshort",function(b,a){"http://"!=b.substr(0,7)&&(b="http://"+b);"/"!=b.substr(b.length-1,1)&&(b+="/");return this.optional(a)||/^(http|https|ftp):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i.test(b)},"Not valid url.");jQuery.validator.addMethod("letterswithbasicpunc",function(b,a){return this.optional(a)||/^[a-z-.,?!()'\"\s]+$/i.test(b)},Localization.Validation.letterswithbasicpunc);
jQuery.validator.addMethod("alphanumericnodash",function(b,a){return this.optional(a)||/^[\sa-zA-Z0-9]+$/i.test(b)},Localization.Validation.alphanumericnodash);jQuery.validator.addMethod("alphanumericwhitespace",function(b,a){return this.optional(a)||/^[a-zA-Z0-9-\s]+$/i.test(b)},Localization.Validation.alphanumericwhitespace);jQuery.validator.addMethod("alphanumeric",function(b,a){return this.optional(a)||/^[a-zA-Z0-9-]+$/i.test(b)},Localization.Validation.alphanumeric);
jQuery.validator.addMethod("lettersonly",function(b,a){return this.optional(a)||/^[a-z]+$/i.test(b)},Localization.Validation.lettersonly);jQuery.validator.addMethod("nowhitespace",function(b,a){return this.optional(a)||/^\S+$/i.test(b)},Localization.Validation.nowhitespace);jQuery.validator.addMethod("ziprange",function(b,a){return this.optional(a)||/^90[2-5]\d\{2}-\d{4}$/.test(b)},Localization.Validation.ziprange);
jQuery.validator.addMethod("integer",function(b,a){return this.optional(a)||/^-?\d+$/.test(b)},Localization.Validation.integer);
jQuery.validator.addMethod("vinUS",function(b){if(17!=b.length)return!1;var a,c,d,f,g,r="ABCDEFGHJKLMNPRSTUVWXYZ".split(""),u=[1,2,3,4,5,6,7,8,1,2,3,4,5,7,9,2,3,4,5,6,7,8,9],n=[8,7,6,5,4,3,2,10,0,9,8,7,6,5,4,3,2],s=0;for(a=0;17>a;a++){f=n[a];d=b.slice(a,a+1);8==a&&(g=d);if(isNaN(d))for(c=0;c<r.length;c++){if(d.toUpperCase()===r[c]){d=u[c];d*=f;isNaN(g)&&8==c&&(g=r[c]);break}}else d*=f;s+=d}b=s%11;10==b&&(b="X");return b==g?!0:!1},Localization.Validation.vinUS);
jQuery.validator.addMethod("dateITA",function(b,a){var c=!1;if(/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(b))var d=b.split("/"),c=parseInt(d[0],10),f=parseInt(d[1],10),d=parseInt(d[2],10),g=new Date(d,f-1,c),c=g.getFullYear()==d&&g.getMonth()==f-1&&g.getDate()==c?!0:!1;else c=!1;return this.optional(a)||c},Localization.Validation.dateITA);!function(b){"function"==typeof define&&define.amd?define(["jquery"],b):b("undefined"!=typeof jQuery?jQuery:window.Zepto)}(function(b){function a(a){var c=a.data;a.isDefaultPrevented()||(a.preventDefault(),b(a.target).ajaxSubmit(c))}function c(a){var c=a.target,d=b(c);if(!d.is("[type=submit],[type=image]")){c=d.closest("[type=submit]");if(0===c.length)return;c=c[0]}var e=this;if(e.clk=c,"image"==c.type)void 0!==a.offsetX?(e.clk_x=a.offsetX,e.clk_y=a.offsetY):"function"==typeof b.fn.offset?(d=d.offset(),
e.clk_x=a.pageX-d.left,e.clk_y=a.pageY-d.top):(e.clk_x=a.pageX-c.offsetLeft,e.clk_y=a.pageY-c.offsetTop);setTimeout(function(){e.clk=e.clk_x=e.clk_y=null},100)}function d(){if(b.fn.ajaxSubmit.debug){var a="[jquery.form] "+Array.prototype.join.call(arguments,"");window.console&&window.console.log?window.console.log(a):window.opera&&window.opera.postError&&window.opera.postError(a)}}var f,g;f=void 0!==b("<input type='file'/>").get(0).files;g=void 0!==window.FormData;var r=!!b.fn.prop;b.fn.attr2=function(){if(!r)return this.attr.apply(this,
arguments);var a=this.prop.apply(this,arguments);return a&&a.jquery||"string"==typeof a?a:this.attr.apply(this,arguments)};b.fn.ajaxSubmit=function(a){function c(e){function f(a){var b=null;try{a.contentWindow&&(b=a.contentWindow.document)}catch(c){d("cannot get iframe.contentWindow document: "+c)}if(b)return b;try{b=a.contentDocument?a.contentDocument:a.document}catch(e){d("cannot get iframe.contentDocument: "+e),b=a.document}return b}function g(){function a(){try{var b=f(z).readyState;d("state = "+
b);b&&"uninitialized"==b.toLowerCase()&&setTimeout(a,50)}catch(c){d("Server abort: ",c," (",c.name,")"),k(C),F&&clearTimeout(F),F=void 0}}var c=p.attr2("target"),e=p.attr2("action"),u=p.attr("enctype")||p.attr("encoding")||"multipart/form-data";w.setAttribute("target",l);(!s||/post/i.test(s))&&w.setAttribute("method","POST");e!=h.url&&w.setAttribute("action",h.url);h.skipEncodingOverride||s&&!/post/i.test(s)||p.attr({encoding:"multipart/form-data",enctype:"multipart/form-data"});h.timeout&&(F=setTimeout(function(){y=
!0;k(G)},h.timeout));var j=[];try{if(h.extraData)for(var n in h.extraData)h.extraData.hasOwnProperty(n)&&j.push(b.isPlainObject(h.extraData[n])&&h.extraData[n].hasOwnProperty("name")&&h.extraData[n].hasOwnProperty("value")?b('<input type="hidden" name="'+h.extraData[n].name+'">').val(h.extraData[n].value).appendTo(w)[0]:b('<input type="hidden" name="'+n+'">').val(h.extraData[n]).appendTo(w)[0]);h.iframeTarget||m.appendTo("body");z.attachEvent?z.attachEvent("onload",k):z.addEventListener("load",k,
!1);setTimeout(a,15);try{w.submit()}catch(t){document.createElement("form").submit.apply(w)}}finally{w.setAttribute("action",e),w.setAttribute("enctype",u),c?w.setAttribute("target",c):p.removeAttr("target"),b(j).remove()}}function k(a){if(!j.aborted&&!E){if(v=f(z),v||(d("cannot access response document"),a=C),a===G&&j)return j.abort("timeout"),void A.reject(j,"timeout");if(a==C&&j)return j.abort("server abort"),void A.reject(j,"error","server abort");if(v&&v.location.href!=h.iframeSrc||y){z.detachEvent?
z.detachEvent("onload",k):z.removeEventListener("load",k,!1);var c;a="success";try{if(y)throw"timeout";var e="xml"==h.dataType||v.XMLDocument||b.isXMLDoc(v);if(d("isXml="+e),!e&&window.opera&&(null===v.body||!v.body.innerHTML)&&--H)return d("requeing onLoad callback, DOM not available"),void setTimeout(k,250);var u=v.body?v.body:v.documentElement;j.responseText=u?u.innerHTML:null;j.responseXML=v.XMLDocument?v.XMLDocument:v;e&&(h.dataType="xml");j.getResponseHeader=function(a){return{"content-type":h.dataType}[a.toLowerCase()]};
u&&(j.status=Number(u.getAttribute("status"))||j.status,j.statusText=u.getAttribute("statusText")||j.statusText);var n=(h.dataType||"").toLowerCase(),s=/(json|script|text)/.test(n);if(s||h.textarea){var p=v.getElementsByTagName("textarea")[0];if(p)j.responseText=p.value,j.status=Number(p.getAttribute("status"))||j.status,j.statusText=p.getAttribute("statusText")||j.statusText;else if(s){var g=v.getElementsByTagName("pre")[0],l=v.getElementsByTagName("body")[0];g?j.responseText=g.textContent?g.textContent:
g.innerText:l&&(j.responseText=l.textContent?l.textContent:l.innerText)}}else"xml"==n&&!j.responseXML&&j.responseText&&(j.responseXML=I(j.responseText));try{var e=j,u=h,q=e.getResponseHeader("content-type")||"",r="xml"===n||!n&&0<=q.indexOf("xml"),B=r?e.responseXML:e.responseText;D=(r&&"parsererror"===B.documentElement.nodeName&&b.error&&b.error("parsererror"),u&&u.dataFilter&&(B=u.dataFilter(B,n)),"string"==typeof B&&("json"===n||!n&&0<=q.indexOf("json")?B=J(B):("script"===n||!n&&0<=q.indexOf("javascript"))&&
b.globalEval(B)),B)}catch(w){a="parsererror",j.error=c=w||a}}catch(x){d("error caught: ",x),a="error",j.error=c=x||a}j.aborted&&(d("upload aborted"),a=null);j.status&&(a=200<=j.status&&300>j.status||304===j.status?"success":"error");"success"===a?(h.success&&h.success.call(h.context,D,"success",j),A.resolve(j.responseText,"success",j),t&&b.event.trigger("ajaxSuccess",[j,h])):a&&(void 0===c&&(c=j.statusText),h.error&&h.error.call(h.context,j,a,c),A.reject(j,"error",c),t&&b.event.trigger("ajaxError",
[j,h,c]));t&&b.event.trigger("ajaxComplete",[j,h]);t&&!--b.active&&b.event.trigger("ajaxStop");h.complete&&h.complete.call(h.context,j,a);E=!0;h.timeout&&clearTimeout(F);setTimeout(function(){h.iframeTarget?m.attr("src",h.iframeSrc):m.remove();j.responseXML=null},100)}}}var n,h,t,l,m,z,j,x,y,F,w=p[0],A=b.Deferred();if(A.abort=function(a){j.abort(a)},e)for(n=0;n<q.length;n++)e=b(q[n]),r?e.prop("disabled",!1):e.removeAttr("disabled");if(h=b.extend(!0,{},b.ajaxSettings,a),h.context=h.context||h,l="jqFormIO"+
(new Date).getTime(),h.iframeTarget?(m=b(h.iframeTarget),x=m.attr2("name"),x?l=x:m.attr2("name",l)):(m=b('<iframe name="'+l+'" src="'+h.iframeSrc+'" />'),m.css({position:"absolute",top:"-1000px",left:"-1000px"})),z=m[0],j={aborted:0,responseText:null,responseXML:null,status:0,statusText:"n/a",getAllResponseHeaders:function(){},getResponseHeader:function(){},setRequestHeader:function(){},abort:function(a){var c="timeout"===a?"timeout":"aborted";d("aborting upload... "+c);this.aborted=1;try{z.contentWindow.document.execCommand&&
z.contentWindow.document.execCommand("Stop")}catch(e){}m.attr("src",h.iframeSrc);j.error=c;h.error&&h.error.call(h.context,j,c,a);t&&b.event.trigger("ajaxError",[j,h,c]);h.complete&&h.complete.call(h.context,j,c)}},t=h.global,t&&0===b.active++&&b.event.trigger("ajaxStart"),t&&b.event.trigger("ajaxSend",[j,h]),h.beforeSend&&!1===h.beforeSend.call(h.context,j,h))return h.global&&b.active--,A.reject(),A;if(j.aborted)return A.reject(),A;(e=w.clk)&&(x=e.name,x&&!e.disabled&&(h.extraData=h.extraData||{},
h.extraData[x]=e.value,"image"==e.type&&(h.extraData[x+".x"]=w.clk_x,h.extraData[x+".y"]=w.clk_y)));var G=1,C=2;x=b("meta[name=csrf-token]").attr("content");(e=b("meta[name=csrf-param]").attr("content"))&&x&&(h.extraData=h.extraData||{},h.extraData[e]=x);h.forceSync?g():setTimeout(g,10);var D,v,E,H=50,I=b.parseXML||function(a,b){return window.ActiveXObject?(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a)):b=(new DOMParser).parseFromString(a,"text/xml"),b&&b.documentElement&&"parsererror"!=
b.documentElement.nodeName?b:null},J=b.parseJSON||function(a){return window.eval("("+a+")")};return A}if(!this.length)return d("ajaxSubmit: skipping submit process - no element selected"),this;var s,e,p=this;"function"==typeof a?a={success:a}:void 0===a&&(a={});s=a.type||this.attr2("method");e=a.url||this.attr2("action");(e=(e="string"==typeof e?b.trim(e):"")||window.location.href||"")&&(e=(e.match(/^([^#]+)/)||[])[1]);a=b.extend(!0,{url:e,success:b.ajaxSettings.success,type:s||b.ajaxSettings.type,
iframeSrc:/^https/i.test(window.location.href||"")?"javascript:false":"about:blank"},a);e={};if(this.trigger("form-pre-serialize",[this,a,e]),e.veto)return d("ajaxSubmit: submit vetoed via form-pre-serialize trigger"),this;if(a.beforeSerialize&&!1===a.beforeSerialize(this,a))return d("ajaxSubmit: submit aborted via beforeSerialize callback"),this;var t=a.traditional;void 0===t&&(t=b.ajaxSettings.traditional);var k,q=[],l=this.formToArray(a.semantic,q);if(a.data&&(a.extraData=a.data,k=b.param(a.data,
t)),a.beforeSubmit&&!1===a.beforeSubmit(l,this,a))return d("ajaxSubmit: submit aborted via beforeSubmit callback"),this;if(this.trigger("form-submit-validate",[l,this,a,e]),e.veto)return d("ajaxSubmit: submit vetoed via form-submit-validate trigger"),this;e=b.param(l,t);k&&(e=e?e+"&"+k:k);"GET"==a.type.toUpperCase()?(a.url+=(0<=a.url.indexOf("?")?"&":"?")+e,a.data=null):a.data=e;var m=[];if(a.resetForm&&m.push(function(){p.resetForm()}),a.clearForm&&m.push(function(){p.clearForm(a.includeHidden)}),
!a.dataType&&a.target){var G=a.success||function(){};m.push(function(c){var d=a.replaceTarget?"replaceWith":"html";b(a.target)[d](c).each(G,arguments)})}else a.success&&m.push(a.success);if(a.success=function(b,c,d){for(var e=a.context||this,f=0,h=m.length;h>f;f++)m[f].apply(e,[b,c,d||p,p])},a.error){var y=a.error;a.error=function(b,c,d){y.apply(a.context||this,[b,c,d,p])}}if(a.complete){var I=a.complete;a.complete=function(b,c){I.apply(a.context||this,[b,c,p])}}k=0<b("input[type=file]:enabled",this).filter(function(){return""!==
b(this).val()}).length;e="multipart/form-data"==p.attr("enctype")||"multipart/form-data"==p.attr("encoding");t=f&&g;d("fileAPI :"+t);var C;if(!1!==a.iframe&&(a.iframe||(k||e)&&!t))a.closeKeepAlive?b.get(a.closeKeepAlive,function(){C=c(l)}):C=c(l);else{if((k||e)&&t){var E=new FormData;for(e=0;e<l.length;e++)E.append(l[e].name,l[e].value);if(a.extraData){var D=b.param(a.extraData,a.traditional).split("&"),J=D.length;k=[];for(e=0;J>e;e++)D[e]=D[e].replace(/\+/g," "),t=D[e].split("="),k.push([decodeURIComponent(t[0]),
decodeURIComponent(t[1])]);for(e=0;e<k.length;e++)k[e]&&E.append(k[e][0],k[e][1])}a.data=null;k=b.extend(!0,{},b.ajaxSettings,a,{contentType:!1,processData:!1,cache:!1,type:s||"POST"});a.uploadProgress&&(k.xhr=function(){var c=b.ajaxSettings.xhr();return c.upload&&c.upload.addEventListener("progress",function(b){var c=0,d=b.loaded||b.position,e=b.total;b.lengthComputable&&(c=Math.ceil(100*(d/e)));a.uploadProgress(b,d,e,c)},!1),c});k.data=null;var H=k.beforeSend;k=(k.beforeSend=function(b,c){c.data=
a.formData?a.formData:E;H&&H.call(this,b,c)},b.ajax(k))}else k=b.ajax(a);C=k}p.removeData("jqxhr").data("jqxhr",C);for(k=0;k<q.length;k++)q[k]=null;return this.trigger("form-submit-notify",[this,a]),this};b.fn.ajaxForm=function(f){if(f=f||{},f.delegation=f.delegation&&b.isFunction(b.fn.on),!f.delegation&&0===this.length){var n=this.selector,s=this.context;return!b.isReady&&n?(d("DOM not ready, queuing ajaxForm"),b(function(){b(n,s).ajaxForm(f)}),this):(d("terminating; zero elements found by selector"+
(b.isReady?"":" (DOM not ready)")),this)}return f.delegation?(b(document).off("submit.form-plugin",this.selector,a).off("click.form-plugin",this.selector,c).on("submit.form-plugin",this.selector,f,a).on("click.form-plugin",this.selector,f,c),this):this.ajaxFormUnbind().bind("submit.form-plugin",f,a).bind("click.form-plugin",f,c)};b.fn.ajaxFormUnbind=function(){return this.unbind("submit.form-plugin click.form-plugin")};b.fn.formToArray=function(a,c){var d=[];if(0===this.length)return d;var e,p=this[0],
g=this.attr("id"),k=a?p.getElementsByTagName("*"):p.elements;if(k&&!/MSIE [678]/.test(navigator.userAgent)&&(k=b(k).get()),g&&(e=b(':input[form="'+g+'"]').get(),e.length&&(k=(k||[]).concat(e))),!k||!k.length)return d;var q,l,m,r,y;e=0;for(r=k.length;r>e;e++)if(m=k[e],q=m.name,q&&!m.disabled)if(a&&p.clk&&"image"==m.type)p.clk==m&&(d.push({name:q,value:b(m).val(),type:m.type}),d.push({name:q+".x",value:p.clk_x},{name:q+".y",value:p.clk_y}));else if(l=b.fieldValue(m,!0),l&&l.constructor==Array){c&&c.push(m);
g=0;for(y=l.length;y>g;g++)d.push({name:q,value:l[g]})}else if(f&&"file"==m.type)if(c&&c.push(m),y=m.files,y.length)for(g=0;g<y.length;g++)d.push({name:q,value:y[g],type:m.type});else d.push({name:q,value:"",type:m.type});else null!==l&&"undefined"!=typeof l&&(c&&c.push(m),d.push({name:q,value:l,type:m.type,required:m.required}));!a&&p.clk&&(k=b(p.clk),l=k[0],(q=l.name)&&!l.disabled&&"image"==l.type&&(d.push({name:q,value:k.val()}),d.push({name:q+".x",value:p.clk_x},{name:q+".y",value:p.clk_y})));
return d};b.fn.formSerialize=function(a){return b.param(this.formToArray(a))};b.fn.fieldSerialize=function(a){var c=[];return this.each(function(){var d=this.name;if(d){var e=b.fieldValue(this,a);if(e&&e.constructor==Array)for(var f=0,g=e.length;g>f;f++)c.push({name:d,value:e[f]});else null!==e&&"undefined"!=typeof e&&c.push({name:this.name,value:e})}}),b.param(c)};b.fn.fieldValue=function(a){for(var c=[],d=0,e=this.length;e>d;d++){var f=b.fieldValue(this[d],a);null===f||"undefined"==typeof f||f.constructor==
Array&&!f.length||(f.constructor==Array?b.merge(c,f):c.push(f))}return c};b.fieldValue=function(a,c){var d=a.name,e=a.type,f=a.tagName.toLowerCase();if(void 0===c&&(c=!0),c&&(!d||a.disabled||"reset"==e||"button"==e||("checkbox"==e||"radio"==e)&&!a.checked||("submit"==e||"image"==e)&&a.form&&a.form.clk!=a||"select"==f&&-1==a.selectedIndex))return null;if("select"==f){var g=a.selectedIndex;if(0>g)return null;for(var d=[],f=a.options,k=(e="select-one"==e)?g+1:f.length,g=e?g:0;k>g;g++){var q=f[g];if(q.selected){var l=
q.value;if(l||(l=q.attributes&&q.attributes.value&&!q.attributes.value.specified?q.text:q.value),e)return l;d.push(l)}}return d}return b(a).val()};b.fn.clearForm=function(a){return this.each(function(){b("input,select,textarea",this).clearFields(a)})};b.fn.clearFields=b.fn.clearInputs=function(a){var c=/^(?:color|date|datetime|email|month|number|password|range|search|tel|text|time|url|week)$/i;return this.each(function(){var d=this.type,e=this.tagName.toLowerCase();c.test(d)||"textarea"==e?this.value=
"":"checkbox"==d||"radio"==d?this.checked=!1:"select"==e?this.selectedIndex=-1:"file"==d?/MSIE/.test(navigator.userAgent)?b(this).replaceWith(b(this).clone(!0)):b(this).val(""):a&&(!0===a&&/hidden/.test(d)||"string"==typeof a&&b(this).is(a))&&(this.value="")})};b.fn.resetForm=function(){return this.each(function(){("function"==typeof this.reset||"object"==typeof this.reset&&!this.reset.nodeType)&&this.reset()})};b.fn.enable=function(a){return void 0===a&&(a=!0),this.each(function(){this.disabled=
!a})};b.fn.selected=function(a){return void 0===a&&(a=!0),this.each(function(){var c=this.type;"checkbox"==c||"radio"==c?this.checked=a:"option"==this.tagName.toLowerCase()&&(c=b(this).parent("select"),a&&c[0]&&"select-one"==c[0].type&&c.find("option").selected(!1),this.selected=a)})};b.fn.ajaxSubmit.debug=!1});

// getQueryVariable
function getQueryVariable(variable) {
    var query = window.location.search.substring(1); // search in parent
    var vars = query.split('&');
    for (var i = 0; i < vars.length; i++) {
        var pair = vars[i].split('=');
        if (decodeURIComponent(pair[0]) == variable) {
            return decodeURIComponent(pair[1]);
        }
    }
}